import { colors } from './colors'

const themeColors = {
  greyLight: {
    'grey-25': '#FDFDFD',
    'grey-50': '#FAFAFA',
    'grey-100': '#F5F5F5',
    'grey-200': '#E9EAEB',
    'grey-300': '#D5D7DA',
    'grey-400': '#A4A7AE',
    'grey-500': '#717680',
    'grey-600': '#535862',
    'grey-700': '#414651',
    'grey-800': '#252B37',
    'grey-900': '#181D27',
    'grey-950': '#0C0E12',
  },
  greyDark: {
    'grey-25': '#FAFAFA',
    'grey-50': '#F7F7F7',
    'grey-100': '#F0F0F1',
    'grey-200': '#ECECED',
    'grey-300': '#CECFD2',
    'grey-400': '#94979C',
    'grey-500': '#85888E',
    'grey-600': '#61656C',
    'grey-700': '#373A41',
    'grey-800': '#22262F',
    'grey-900': '#13161B',
    'grey-950': '#0C0E12',
  },
}

export const themes = {
  light: {
    ...themeColors.greyLight,
    'text-primary': themeColors.greyLight['grey-900'],
    'text-primary-on-brand': colors.white,
    'text-secondary': themeColors.greyLight['grey-700'],
    'text-secondary_hover': themeColors.greyLight['grey-800'],
    'text-secondary_on-brand': colors.white,
    'text-tertiary': themeColors.greyLight['grey-500'],
    'text-tertiary_hover': themeColors.greyLight['grey-700'],
    'text-tertiary_on-brand': colors.white,
    'text-quaternary': themeColors.greyLight['grey-400'],
    'text-quaternary_on-brand': colors.white,
    'text-white': colors.white,
    'text-disabled': themeColors.greyLight['grey-400'],
    'text-placeholder': themeColors.greyLight['grey-500'],
    'text-placeholder_subtle': themeColors.greyLight['grey-300'],
    'text-brand-primary': colors.primary[700],
    'text-brand-secondary': colors.primary[600],
    'text-brand-secondary_hover': colors.primary[700],
    'text-brand-tertiary': colors.primary[500],
    'text-brand-tertiary_alt': colors.primary[600],
    'text-error-primary': colors.error[600],
    'text-error-primary_hover': colors.error[700],
    'text-warning-primary': colors.warning[600],
    'text-success-primary': colors.success[600],

    // Border tokens
    'border-primary': themeColors.greyLight['grey-300'],
    'border-primary-inverted': 'rgba(255, 255, 255, 0.08)',
    'border-secondary': themeColors.greyLight['grey-200'],
    'border-secondary_alt': 'rgba(0, 0, 0, 0.08)',
    'border-tertiary': themeColors.greyLight['grey-100'],
    'border-disabled': themeColors.greyLight['grey-300'],
    'border-disabled_subtle': themeColors.greyLight['grey-200'],
    'border-brand': colors.primary[700],
    'border-brand_alt': colors.primary[600],
    'border-error': colors.error[500],
    'border-error_subtle': colors.error[300],
    'border-always-white': themeColors.greyLight['grey-100'],

    // Foreground tokens
    'fg-primary': themeColors.greyLight['grey-900'],
    'fg-secondary': themeColors.greyLight['grey-700'],
    'fg-secondary_hover': themeColors.greyLight['grey-800'],
    'fg-tertiary': themeColors.greyLight['grey-600'],
    'fg-tertiary_hover': themeColors.greyLight['grey-700'],
    'fg-quaternary': themeColors.greyLight['grey-400'],
    'fg-quaternary_hover': themeColors.greyLight['grey-500'],
    'fg-white': colors.white,
    'fg-disabled': themeColors.greyLight['grey-400'],
    'fg-disabled_subtle': themeColors.greyLight['grey-300'],
    'fg-brand-primary': colors.primary[600],
    'fg-brand-primary_alt': themeColors.greyLight['grey-600'],
    'fg-brand-primary-600': colors.primary[600],
    'fg-brand-secondary': colors.primary[500],
    'fg-brand-secondary_alt': colors.primary[500],
    'fg-brand-secondary_hover': colors.primary[600],
    'fg-error-primary': colors.error[600],
    'fg-error-secondary': colors.error[500],
    'fg-warning-primary': colors.warning[600],
    'fg-warning-secondary': colors.warning[500],
    'fg-success-primary': colors.success[600],
    'fg-success-secondary': colors.success[500],

    // Background tokens
    'bg-primary': colors.white,
    'bg-primary_alt': colors.white,
    'bg-primary_hover': themeColors.greyLight['grey-50'],
    'bg-primary-solid': themeColors.greyLight['grey-950'],
    'bg-secondary': themeColors.greyLight['grey-50'],
    'bg-secondary_alt': themeColors.greyLight['grey-50'],
    'bg-secondary_hover': themeColors.greyLight['grey-100'],
    'bg-secondary_subtle': themeColors.greyLight['grey-25'],
    'bg-secondary-solid': themeColors.greyLight['grey-600'],
    'bg-tertiary': themeColors.greyLight['grey-100'],
    'bg-quaternary': themeColors.greyLight['grey-200'],
    'bg-active': themeColors.greyLight['grey-50'],
    'bg-disabled': themeColors.greyLight['grey-100'],
    'bg-disabled_subtle': themeColors.greyLight['grey-50'],
    'bg-overlay': themeColors.greyLight['grey-950'],
    'bg-overlay-transparent': 'rgba(10, 13, 18, 0.5)',
    'bg-brand-primary': colors.primary[50],
    'bg-brand-primary_alt': colors.primary[50],
    'bg-brand-secondary': colors.primary[100],
    'bg-brand-solid': colors.primary[700],
    'bg-brand-solid_hover': colors.primary[800],
    'bg-brand-section': colors.primary[800],
    'bg-brand-section_subtle': colors.primary[700],
    'bg-error-primary': colors.error[50],
    'bg-error-secondary': colors.error[100],
    'bg-error-solid': colors.error[600],
    'bg-warning-primary': colors.warning[50],
    'bg-warning-secondary': colors.warning[100],
    'bg-warning-solid': colors.warning[600],
    'bg-success-primary': colors.success[50],
    'bg-success-secondary': colors.success[100],
    'bg-success-solid': colors.success[600],

    // Shadow tokens
    'shadow-xs': 'rgba(10, 13, 18, 0.05)',
    'shadow-sm_01': 'rgba(10, 13, 18, 0.10)',
    'shadow-sm_02': 'rgba(10, 13, 18, 0.10)',
    'shadow-md_01': 'rgba(10, 13, 18, 0.10)',
    'shadow-md_02': 'rgba(10, 13, 18, 0.06)',
    'shadow-lg_01': 'rgba(10, 13, 18, 0.08)',
    'shadow-lg_02': 'rgba(10, 13, 18, 0.03)',
    'shadow-lg_03': 'rgba(10, 13, 18, 0.04)',
    'shadow-xl_01': 'rgba(10, 13, 18, 0.08)',
    'shadow-xl_02': 'rgba(10, 13, 18, 0.03)',
    'shadow-xl_03': 'rgba(10, 13, 18, 0.04)',
    'shadow-2xl_01': 'rgba(10, 13, 18, 0.18)',
    'shadow-2xl_02': 'rgba(10, 13, 18, 0.04)',
    'shadow-3xl_01': 'rgba(10, 13, 18, 0.14)',
    'shadow-3xl_02': 'rgba(10, 13, 18, 0.04)',

    //utility brand
    'utility-brand-25': colors.primary[25],
    'utility-brand-50': colors.primary[50],
    'utility-brand-100': colors.primary[100],
    'utility-brand-200': colors.primary[200],
    'utility-brand-300': colors.primary[300],
    'utility-brand-400': colors.primary[400],
    'utility-brand-500': colors.primary[500],
    'utility-brand-600': colors.primary[600],
    'utility-brand-700': colors.primary[700],
    'utility-brand-800': colors.primary[800],
    'utility-brand-900': colors.primary[900],
    'utility-brand-950': colors.primary[950],

    //utility error
    'utility-error-50': colors.error[50],
    'utility-error-100': colors.error[100],
    'utility-error-200': colors.error[200],
    'utility-error-300': colors.error[300],
    'utility-error-400': colors.error[400],
    'utility-error-500': colors.error[500],
    'utility-error-600': colors.error[600],
    'utility-error-700': colors.error[700],

    //utility warning
    'utility-warning-50': colors.warning[50],
    'utility-warning-100': colors.warning[100],
    'utility-warning-200': colors.warning[200],
    'utility-warning-300': colors.warning[300],
    'utility-warning-400': colors.warning[400],
    'utility-warning-500': colors.warning[500],
    'utility-warning-600': colors.warning[600],
    'utility-warning-700': colors.warning[700],

    //utility success
    'utility-success-50': colors.success[50],
    'utility-success-100': colors.success[100],
    'utility-success-200': colors.success[200],
    'utility-success-300': colors.success[300],
    'utility-success-400': colors.success[400],
    'utility-success-500': colors.success[500],
    'utility-success-600': colors.success[600],
    'utility-success-700': colors.success[700],

    //toggle
    'toggle-border': themeColors.greyLight['grey-300'],
    'toggle-slim-border_pressed': colors.primary[700],
    'toggle-slim-border_pressed-hover': colors.primary[800],
    'toggle-button_fg-disabled': themeColors.greyLight['grey-50'],

    //focus ring
    'focus-ring': colors.primary[500],
    'focus-ring-error': colors.error[500],

    //skeleton
    'skeleton-base': themeColors.greyLight['grey-300'],
    'skeleton-highlight': themeColors.greyLight['grey-200'],
  },
  dark: {
    ...themeColors.greyDark,
    'text-primary': themeColors.greyDark['grey-50'],
    'text-primary-on-brand': themeColors.greyDark['grey-50'],
    'text-secondary': themeColors.greyDark['grey-300'],
    'text-secondary_hover': themeColors.greyDark['grey-200'],
    'text-secondary_on-brand': themeColors.greyDark['grey-300'],
    'text-tertiary': themeColors.greyDark['grey-400'],
    'text-tertiary_hover': themeColors.greyDark['grey-300'],
    'text-tertiary_on-brand': themeColors.greyDark['grey-400'],
    'text-quaternary': themeColors.greyDark['grey-400'],
    'text-quaternary_on-brand': themeColors.greyDark['grey-400'],
    'text-white': colors.white,
    'text-disabled': themeColors.greyDark['grey-500'],
    'text-placeholder': themeColors.greyDark['grey-500'],
    'text-placeholder_subtle': themeColors.greyDark['grey-700'],
    'text-brand-primary': themeColors.greyDark['grey-50'],
    'text-brand-secondary': themeColors.greyDark['grey-300'],
    'text-brand-secondary_hover': themeColors.greyDark['grey-200'],
    'text-brand-tertiary': themeColors.greyDark['grey-400'],
    'text-brand-tertiary_alt': themeColors.greyDark['grey-50'],
    'text-error-primary': colors.error[400],
    'text-error-primary_hover': colors.error[300],
    'text-warning-primary': colors.warning[400],
    'text-success-primary': colors.success[400],

    // Border tokens
    'border-primary': themeColors.greyDark['grey-700'],
    'border-primary-inverted': themeColors.greyDark['grey-800'],
    'border-secondary': themeColors.greyDark['grey-800'],
    'border-secondary_alt': themeColors.greyDark['grey-700'],
    'border-tertiary': themeColors.greyDark['grey-800'],
    'border-disabled': themeColors.greyDark['grey-700'],
    'border-disabled_subtle': themeColors.greyDark['grey-800'],
    'border-brand': colors.primary[400],
    'border-brand_alt': colors.primary[600],
    'border-error': colors.error[400],
    'border-error_subtle': colors.error[500],
    'border-always-white': themeColors.greyDark['grey-100'],

    // Foreground tokens
    'fg-primary': colors.white,
    'fg-secondary': themeColors.greyDark['grey-300'],
    'fg-secondary_hover': themeColors.greyDark['grey-200'],
    'fg-tertiary': themeColors.greyDark['grey-400'],
    'fg-tertiary_hover': themeColors.greyDark['grey-300'],
    'fg-quaternary': themeColors.greyDark['grey-600'],
    'fg-quaternary_hover': themeColors.greyDark['grey-500'],
    'fg-white': colors.white,
    'fg-disabled': themeColors.greyDark['grey-500'],
    'fg-disabled_subtle': themeColors.greyDark['grey-600'],
    'fg-brand-primary': colors.primary[500],
    'fg-brand-primary_alt': themeColors.greyDark['grey-300'],
    'fg-brand-primary-600': colors.primary[500],
    'fg-brand-secondary': colors.primary[500],
    'fg-brand-secondary_alt': themeColors.greyDark['grey-600'],
    'fg-brand-secondary_hover': themeColors.greyDark['grey-500'],
    'fg-error-primary': colors.error[500],
    'fg-error-secondary': colors.error[400],
    'fg-warning-primary': colors.warning[500],
    'fg-warning-secondary': colors.warning[400],
    'fg-success-primary': colors.success[500],
    'fg-success-secondary': colors.success[400],

    // Background tokens
    'bg-primary': themeColors.greyDark['grey-950'],
    'bg-primary_alt': themeColors.greyDark['grey-900'],
    'bg-primary_hover': themeColors.greyDark['grey-800'],
    'bg-primary-solid': themeColors.greyDark['grey-900'],
    'bg-secondary': themeColors.greyDark['grey-900'],
    'bg-secondary_alt': themeColors.greyDark['grey-950'],
    'bg-secondary_hover': themeColors.greyDark['grey-800'],
    'bg-secondary_subtle': themeColors.greyDark['grey-900'],
    'bg-secondary-solid': themeColors.greyDark['grey-600'],
    'bg-tertiary': themeColors.greyDark['grey-800'],
    'bg-quaternary': themeColors.greyDark['grey-700'],
    'bg-active': themeColors.greyDark['grey-800'],
    'bg-disabled': themeColors.greyDark['grey-800'],
    'bg-disabled_subtle': themeColors.greyDark['grey-900'],
    'bg-overlay': themeColors.greyDark['grey-800'],
    'bg-overlay-transparent': 'rgba(34, 38, 47, 0.5)',
    'bg-brand-primary': colors.primary[975],
    'bg-brand-primary_alt': themeColors.greyDark['grey-900'],
    'bg-brand-secondary': colors.primary[950],
    'bg-brand-solid': colors.primary[600],
    'bg-brand-solid_hover': colors.primary[500],
    'bg-brand-section': themeColors.greyDark['grey-900'],
    'bg-brand-section_subtle': themeColors.greyDark['grey-950'],
    'bg-error-primary': colors.error[950],
    'bg-error-secondary': colors.error[600],
    'bg-error-solid': colors.error[600],
    'bg-warning-primary': colors.warning[950],
    'bg-warning-secondary': colors.warning[600],
    'bg-warning-solid': colors.warning[600],
    'bg-success-primary': colors.success[950],
    'bg-success-secondary': colors.success[600],
    'bg-success-solid': colors.success[600],

    // Shadow tokens
    'shadow-xs': 'transparent',
    'shadow-sm_01': 'transparent',
    'shadow-sm_02': 'transparent',
    'shadow-md_01': 'transparent',
    'shadow-md_02': 'transparent',
    'shadow-lg_01': 'transparent',
    'shadow-lg_02': 'transparent',
    'shadow-lg_03': 'transparent',
    'shadow-xl_01': 'transparent',
    'shadow-xl_02': 'transparent',
    'shadow-xl_03': 'transparent',
    'shadow-2xl_01': 'transparent',
    'shadow-2xl_02': 'transparent',
    'shadow-3xl_01': 'transparent',
    'shadow-3xl_02': 'transparent',

    //utility brand
    'utility-brand-50': colors.primary[950],
    'utility-brand-100': colors.primary[900],
    'utility-brand-200': colors.primary[800],
    'utility-brand-300': colors.primary[700],
    'utility-brand-400': colors.primary[600],
    'utility-brand-500': colors.primary[500],
    'utility-brand-600': colors.primary[400],
    'utility-brand-700': colors.primary[300],
    'utility-brand-800': colors.primary[200],
    'utility-brand-900': colors.primary[100],
    'utility-brand-950': colors.primary[50],

    //utility error
    'utility-error-50': colors.error[950],
    'utility-error-100': colors.error[900],
    'utility-error-200': colors.error[800],
    'utility-error-300': colors.error[700],
    'utility-error-400': colors.error[600],
    'utility-error-500': colors.error[500],
    'utility-error-600': colors.error[400],
    'utility-error-700': colors.error[300],

    //utility warning
    'utility-warning-50': colors.warning[950],
    'utility-warning-100': colors.warning[900],
    'utility-warning-200': colors.warning[800],
    'utility-warning-300': colors.warning[700],
    'utility-warning-400': colors.warning[600],
    'utility-warning-500': colors.warning[500],
    'utility-warning-600': colors.warning[400],
    'utility-warning-700': colors.warning[300],

    //utility success
    'utility-success-50': colors.success[950],
    'utility-success-100': colors.success[900],
    'utility-success-200': colors.success[800],
    'utility-success-300': colors.success[700],
    'utility-success-400': colors.success[600],
    'utility-success-500': colors.success[500],
    'utility-success-600': colors.success[400],
    'utility-success-700': colors.success[300],

    //toggle
    'toggle-border': 'transparent',
    'toggle-slim-border_pressed': 'transparent',
    'toggle-slim-border_pressed-hover': 'transparent',
    'toggle-button_fg-disabled': themeColors.greyDark['grey-600'],

    //focus ring
    'focus-ring': colors.primary[500],
    'focus-ring-error': colors.error[500],

    //skeleton
    'skeleton-base': themeColors.greyDark['grey-700'],
    'skeleton-highlight': themeColors.greyDark['grey-800'],
  },
}
